tests = {
    1: [
        {"question": "What is the capital of France?", "options": ["Berlin", "Madrid", "Paris", "Rome"], "answer": "Paris"},
        {"question": "Which gas do humans need to breathe?", "options": ["Hydrogen", "Oxygen", "Nitrogen", "Carbon"], "answer": "Oxygen"},
        {"question": "5 + 7 = ?", "options": ["10", "12", "11", "13"], "answer": "12"},
        {"question": "Who discovered gravity?", "options": ["Einstein", "Newton", "Galileo", "Tesla"], "answer": "Newton"},
        {"question": "In which year did India become independent?", "options": ["1942", "1947", "1950", "1960"], "answer": "1947"},
        {"question": "What is H2O?", "options": ["Oxygen", "Hydrogen", "Water", "Helium"], "answer": "Water"},
        {"question": "Who is known as the father of computers?", "options": ["Charles Babbage", "Bill Gates", "Steve Jobs", "Alan Turing"], "answer": "Charles Babbage"},
        {"question": "2 x 8 = ?", "options": ["14", "16", "18", "12"], "answer": "16"},
        {"question": "What is the largest mammal?", "options": ["Elephant", "Blue Whale", "Giraffe", "Shark"], "answer": "Blue Whale"},
        {"question": "Who wrote the Indian National Anthem?", "options": ["Tagore", "Gandhi", "Tilak", "Nehru"], "answer": "Tagore"},
        {"question": "What planet do we live on?", "options": ["Mars", "Venus", "Earth", "Jupiter"], "answer": "Earth"},
        {"question": "Which is a primary color?", "options": ["Purple", "Green", "Red", "Brown"], "answer": "Red"},
        {"question": "The Taj Mahal is located in?", "options": ["Delhi", "Agra", "Mumbai", "Jaipur"], "answer": "Agra"},
        {"question": "What is 25 ÷ 5?", "options": ["4", "5", "6", "7"], "answer": "5"},
        {"question": "Who is the current President of India (as of 2024)?", "options": ["Droupadi Murmu", "Narendra Modi", "Ramnath Kovind", "Sonia Gandhi"], "answer": "Droupadi Murmu"},
        {"question": "What is the boiling point of water?", "options": ["90°C", "100°C", "120°C", "80°C"], "answer": "100°C"},
        {"question": "Which one is a herbivore?", "options": ["Tiger", "Lion", "Cow", "Wolf"], "answer": "Cow"},
        {"question": "10 x 10 = ?", "options": ["100", "110", "90", "120"], "answer": "100"},
        {"question": "What does DNA stand for?", "options": ["Deoxyribo Nucleic Acid", "Deoxy Nitrate Acid", "Dynamic Acid", "Double Acid"], "answer": "Deoxyribo Nucleic Acid"},
        {"question": "What is the national animal of India?", "options": ["Elephant", "Lion", "Tiger", "Panther"], "answer": "Tiger"},
        {"question": "Who wrote 'Discovery of India'?", "options": ["Gandhi", "Ambedkar", "Nehru", "Patel"], "answer": "Nehru"},
        {"question": "Which is the smallest continent?", "options": ["Asia", "Australia", "Europe", "Africa"], "answer": "Australia"},
        {"question": "Who invented the light bulb?", "options": ["Newton", "Edison", "Faraday", "Tesla"], "answer": "Edison"},
        {"question": "What is the freezing point of water?", "options": ["0°C", "10°C", "32°C", "50°C"], "answer": "0°C"},
        {"question": "3^3 equals?", "options": ["9", "27", "18", "21"], "answer": "27"},
        {"question": "What is the capital of Australia?", "options": ["Sydney", "Melbourne", "Canberra", "Perth"], "answer": "Canberra"},
        {"question": "Which ocean is the largest?", "options": ["Atlantic", "Indian", "Arctic", "Pacific"], "answer": "Pacific"},
        {"question": "Who discovered penicillin?", "options": ["Alexander Fleming", "Marie Curie", "Newton", "Darwin"], "answer": "Alexander Fleming"},
        {"question": "Which festival is known as the festival of lights?", "options": ["Holi", "Eid", "Diwali", "Christmas"], "answer": "Diwali"},
        {"question": "The Indian Parliament has how many houses?", "options": ["1", "2", "3", "4"], "answer": "2"}
    ],

    2: [
        {"question": "Who invented the telephone?", "options": ["Edison", "Newton", "Bell", "Tesla"], "answer": "Bell"},
        {"question": "Which is the smallest planet?", "options": ["Mars", "Mercury", "Venus", "Pluto"], "answer": "Mercury"},
        {"question": "What is 9 x 8?", "options": ["72", "81", "64", "70"], "answer": "72"},
        {"question": "In which continent is Egypt?", "options": ["Europe", "Asia", "Africa", "Australia"], "answer": "Africa"},
        {"question": "Who wrote the Indian National Anthem?", "options": ["Tagore", "Premchand", "Nehru", "Tilak"], "answer": "Tagore"},
        {"question": "Water boils at?", "options": ["90°C", "100°C", "110°C", "120°C"], "answer": "100°C"},
        {"question": "Which metal is liquid at room temp?", "options": ["Iron", "Mercury", "Aluminum", "Zinc"], "answer": "Mercury"},
        {"question": "Area of square (side=4)?", "options": ["8", "12", "16", "20"], "answer": "16"},
        {"question": "Who discovered gravity?", "options": ["Einstein", "Newton", "Galileo", "Curie"], "answer": "Newton"},
        {"question": "First Indian Prime Minister?", "options": ["Nehru", "Gandhi", "Patel", "Rajaji"], "answer": "Nehru"},
        {"question": "Which is the longest river?", "options": ["Amazon", "Nile", "Ganga", "Yangtze"], "answer": "Nile"},
        {"question": "What is 25% of 80?", "options": ["20", "15", "30", "25"], "answer": "20"},
        {"question": "Photosynthesis happens in?", "options": ["Root", "Stem", "Leaf", "Flower"], "answer": "Leaf"},
        {"question": "Independence Day is on?", "options": ["Aug 14", "Aug 15", "Jan 26", "Oct 2"], "answer": "Aug 15"},
        {"question": "Which is a prime number?", "options": ["4", "9", "7", "15"], "answer": "7"},
        {"question": "Taj Mahal built by?", "options": ["Akbar", "Shah Jahan", "Aurangzeb", "Babur"], "answer": "Shah Jahan"},
        {"question": "Boiling point of water in F?", "options": ["100", "180", "212", "200"], "answer": "212"},
        {"question": "Sun is a?", "options": ["Planet", "Star", "Comet", "Asteroid"], "answer": "Star"},
        {"question": "Current PM of India (2024)?", "options": ["Modi", "Rahul", "Manmohan", "Amit Shah"], "answer": "Modi"},
        {"question": "Speed = Distance / ?", "options": ["Time", "Mass", "Velocity", "Area"], "answer": "Time"},
        {"question": "Which state is Hyderabad in?", "options": ["AP", "Telangana", "Karnataka", "Odisha"], "answer": "Telangana"},
        {"question": "Decimal of 1/4?", "options": ["0.5", "0.25", "0.75", "0.2"], "answer": "0.25"},
        {"question": "Gas used in balloons?", "options": ["Hydrogen", "Helium", "Oxygen", "Nitrogen"], "answer": "Helium"},
        {"question": "Largest bone in human body?", "options": ["Femur", "Tibia", "Spine", "Humerus"], "answer": "Femur"},
        {"question": "Which is not a programming language?", "options": ["Python", "Java", "HTML", "Windows"], "answer": "Windows"},
        {"question": "SI unit of force?", "options": ["Joule", "Newton", "Pascal", "Watt"], "answer": "Newton"},
        {"question": "How many continents?", "options": ["5", "6", "7", "8"], "answer": "7"},
        {"question": "National animal of India?", "options": ["Elephant", "Tiger", "Lion", "Cheetah"], "answer": "Tiger"},
        {"question": "1 GB = ? MB", "options": ["1000", "1024", "500", "2048"], "answer": "1024"},
        {"question": "Which is a herbivore?", "options": ["Lion", "Wolf", "Goat", "Tiger"], "answer": "Goat"}
    ],

    3: [
        {"question": "What color is chlorophyll?", "options": ["Red", "Blue", "Green", "Yellow"], "answer": "Green"},
        {"question": "Currency of Japan?", "options": ["Yuan", "Won", "Yen", "Baht"], "answer": "Yen"},
        {"question": "7² = ?", "options": ["49", "42", "36", "56"], "answer": "49"},
        {"question": "First President of India?", "options": ["Nehru", "Radhakrishnan", "Rajendra Prasad", "Zakir Hussain"], "answer": "Rajendra Prasad"},
        {"question": "Organ that pumps blood?", "options": ["Liver", "Heart", "Lungs", "Brain"], "answer": "Heart"},
        {"question": "Which is not a browser?", "options": ["Chrome", "Firefox", "Opera", "Windows"], "answer": "Windows"},
        {"question": "Which is an odd number?", "options": ["8", "12", "9", "14"], "answer": "9"},
        {"question": "Largest desert?", "options": ["Sahara", "Gobi", "Thar", "Arctic"], "answer": "Sahara"},
        {"question": "Water formula?", "options": ["CO2", "H2O", "NaCl", "O2"], "answer": "H2O"},
        {"question": "Father of Computers?", "options": ["Babbage", "Jobs", "Gates", "Turing"], "answer": "Babbage"},
        {"question": "Color of Indian flag top?", "options": ["Green", "White", "Saffron", "Blue"], "answer": "Saffron"},
        {"question": "Opposite of 'hot'?", "options": ["Fire", "Burn", "Cold", "Warm"], "answer": "Cold"},
        {"question": "How many sides in hexagon?", "options": ["5", "6", "7", "8"], "answer": "6"},
        {"question": "Full form of WWW?", "options": ["World Whole Web", "Wide World Web", "World Wide Web", "Web Wide World"], "answer": "World Wide Web"},
        {"question": "Who is APJ Abdul Kalam?", "options": ["Scientist", "Singer", "Actor", "Dancer"], "answer": "Scientist"},
        {"question": "Which is a reptile?", "options": ["Frog", "Snake", "Fish", "Whale"], "answer": "Snake"},
        {"question": "One week has how many days?", "options": ["5", "6", "7", "8"], "answer": "7"},
        {"question": "Which is not a sense organ?", "options": ["Eye", "Nose", "Liver", "Ear"], "answer": "Liver"},
        {"question": "Largest ocean?", "options": ["Atlantic", "Indian", "Pacific", "Arctic"], "answer": "Pacific"},
        {"question": "10 × 10 = ?", "options": ["100", "110", "90", "120"], "answer": "100"},
        {"question": "CPU is part of?", "options": ["Software", "Hardware", "Electricity", "Cloud"], "answer": "Hardware"},
        {"question": "Hindi is national language of?", "options": ["Nepal", "India", "Bangladesh", "Pakistan"], "answer": "India"},
        {"question": "Sun rises in?", "options": ["West", "North", "South", "East"], "answer": "East"},
        {"question": "Which one is a bird?", "options": ["Bat", "Sparrow", "Butterfly", "Bee"], "answer": "Sparrow"},
        {"question": "How many hours in a day?", "options": ["12", "24", "60", "30"], "answer": "24"},
        {"question": "Which is man-made?", "options": ["River", "Mountain", "Bridge", "Forest"], "answer": "Bridge"},
        {"question": "Freezing point of water?", "options": ["0°C", "100°C", "50°C", "25°C"], "answer": "0°C"},
        {"question": "Planet with rings?", "options": ["Saturn", "Mars", "Earth", "Venus"], "answer": "Saturn"},
        {"question": "How many letters in alphabet?", "options": ["25", "26", "27", "28"], "answer": "26"},
        {"question": "Which is not an input device?", "options": ["Mouse", "Keyboard", "Monitor", "Scanner"], "answer": "Monitor"}
    ],

    4: [
    {"question": "Which country is known as the Land of the Rising Sun?", "options": ["China", "Japan", "Thailand", "India"], "answer": "Japan"},
    {"question": "Largest mammal?", "options": ["Elephant", "Blue Whale", "Giraffe", "Hippo"], "answer": "Blue Whale"},
    {"question": "What is the capital of Australia?", "options": ["Sydney", "Melbourne", "Canberra", "Perth"], "answer": "Canberra"},
    {"question": "Which vitamin is gained from sunlight?", "options": ["A", "B", "C", "D"], "answer": "D"},
    {"question": "Who discovered America?", "options": ["Vasco da Gama", "Columbus", "Newton", "Magellan"], "answer": "Columbus"},
    {"question": "Which planet is closest to the sun?", "options": ["Earth", "Venus", "Mercury", "Mars"], "answer": "Mercury"},
    {"question": "Freedom struggle leader in South Africa?", "options": ["Mandela", "Gandhi", "Obama", "Churchill"], "answer": "Mandela"},
    {"question": "How many zeros in one crore?", "options": ["5", "6", "7", "8"], "answer": "7"},
    {"question": "Which gas is used in refrigerators?", "options": ["Nitrogen", "Ammonia", "Hydrogen", "Oxygen"], "answer": "Ammonia"},
    {"question": "Tsunami is caused by?", "options": ["Cyclone", "Flood", "Earthquake", "Thunderstorm"], "answer": "Earthquake"},
    {"question": "What shape is the Earth?", "options": ["Flat", "Square", "Sphere", "Oval"], "answer": "Sphere"},
    {"question": "Indian state famous for tea?", "options": ["Goa", "Assam", "Punjab", "Gujarat"], "answer": "Assam"},
    {"question": "5² = ?", "options": ["10", "20", "25", "15"], "answer": "25"},
    {"question": "Which is a green gas?", "options": ["Ozone", "Methane", "CO₂", "Helium"], "answer": "Ozone"},
    {"question": "How many players in cricket team?", "options": ["10", "11", "12", "9"], "answer": "11"},
    {"question": "Which is an input device?", "options": ["Monitor", "Printer", "Mouse", "Speaker"], "answer": "Mouse"},
    {"question": "Which festival is of lights?", "options": ["Holi", "Eid", "Diwali", "Baisakhi"], "answer": "Diwali"},
    {"question": "Which planet has most moons?", "options": ["Earth", "Mars", "Jupiter", "Saturn"], "answer": "Saturn"},
    {"question": "Which is a non-metal?", "options": ["Copper", "Iron", "Carbon", "Zinc"], "answer": "Carbon"},
    {"question": "What is 1000 - 345?", "options": ["655", "675", "665", "645"], "answer": "655"},
    {"question": "Full form of ATM?", "options": ["Auto Teller Machine", "Automated Teller Machine", "Any Time Money", "Auto Time Machine"], "answer": "Automated Teller Machine"},
    {"question": "Indian festival of harvest?", "options": ["Raksha Bandhan", "Bihu", "Dussehra", "Diwali"], "answer": "Bihu"},
    {"question": "Which one is a software?", "options": ["Keyboard", "MS Word", "Monitor", "RAM"], "answer": "MS Word"},
    {"question": "Which one is a leap year?", "options": ["2022", "2023", "2024", "2025"], "answer": "2024"},
    {"question": "Which is a herb?", "options": ["Bamboo", "Mango", "Tulsi", "Neem"], "answer": "Tulsi"},
    {"question": "Which state is known as God's Own Country?", "options": ["Goa", "Kerala", "Himachal", "Rajasthan"], "answer": "Kerala"},
    {"question": "How many seconds in a minute?", "options": ["60", "100", "45", "30"], "answer": "60"},
    {"question": "Which is not a vowel?", "options": ["A", "E", "U", "Z"], "answer": "Z"},
    {"question": "Mahatma Gandhi was born in?", "options": ["Delhi", "Porbandar", "Mumbai", "Ahmedabad"], "answer": "Porbandar"},
    {"question": "Which is a hill station?", "options": ["Chennai", "Manali", "Hyderabad", "Jaipur"], "answer": "Manali"}
],

    5: [
    {"question": "Which organ helps us breathe?", "options": ["Heart", "Lung", "Liver", "Kidney"], "answer": "Lung"},
    {"question": "National flower of India?", "options": ["Rose", "Lily", "Lotus", "Sunflower"], "answer": "Lotus"},
    {"question": "What is 15 × 2?", "options": ["20", "25", "30", "35"], "answer": "30"},
    {"question": "Which is a search engine?", "options": ["Google", "Excel", "Word", "Windows"], "answer": "Google"},
    {"question": "Capital of Andhra Pradesh?", "options": ["Amaravati", "Vijayawada", "Hyderabad", "Vizag"], "answer": "Amaravati"},
    {"question": "Light travels in?", "options": ["Zigzag", "Straight line", "Circle", "Square"], "answer": "Straight line"},
    {"question": "Which is a carnivore?", "options": ["Cow", "Deer", "Lion", "Goat"], "answer": "Lion"},
    {"question": "What comes after 999?", "options": ["1000", "100", "1100", "200"], "answer": "1000"},
    {"question": "Primary colors are?", "options": ["Red, Blue, Green", "Red, Yellow, Blue", "Yellow, Green, Orange", "Red, White, Blue"], "answer": "Red, Yellow, Blue"},
    {"question": "How many fingers on one hand?", "options": ["4", "5", "6", "7"], "answer": "5"},
    {"question": "National bird of India?", "options": ["Swan", "Peacock", "Parrot", "Pigeon"], "answer": "Peacock"},
    {"question": "Where do fish live?", "options": ["Air", "Land", "Water", "Soil"], "answer": "Water"},
    {"question": "5 + 6 × 2 = ?", "options": ["22", "17", "16", "11"], "answer": "17"},
    {"question": "Largest land animal?", "options": ["Elephant", "Horse", "Tiger", "Lion"], "answer": "Elephant"},
    {"question": "Triangle has how many sides?", "options": ["2", "3", "4", "5"], "answer": "3"},
    {"question": "Which planet is blue?", "options": ["Mars", "Neptune", "Venus", "Jupiter"], "answer": "Neptune"},
    {"question": "Which is used to write?", "options": ["Eraser", "Pen", "Bag", "Scale"], "answer": "Pen"},
    {"question": "Where is Red Fort?", "options": ["Mumbai", "Delhi", "Kolkata", "Chennai"], "answer": "Delhi"},
    {"question": "How many legs does a spider have?", "options": ["6", "8", "4", "10"], "answer": "8"},
    {"question": "Opposite of 'open'?", "options": ["Out", "In", "Closed", "Up"], "answer": "Closed"},
    {"question": "2² = ?", "options": ["2", "4", "6", "8"], "answer": "4"},
    {"question": "Sun is seen in the?", "options": ["Night", "Morning", "Evening", "Midnight"], "answer": "Morning"},
    {"question": "Which is the outermost planet?", "options": ["Neptune", "Mars", "Earth", "Venus"], "answer": "Neptune"},
    {"question": "Busiest railway station in India?", "options": ["Delhi", "Mumbai CST", "Howrah", "Chennai Central"], "answer": "Howrah"},
    {"question": "How many wheels in an auto?", "options": ["2", "3", "4", "5"], "answer": "3"},
    {"question": "Which one is a month?", "options": ["Monday", "March", "Morning", "Minute"], "answer": "March"},
    {"question": "Which one can fly?", "options": ["Cat", "Tiger", "Crow", "Dog"], "answer": "Crow"},
    {"question": "How many arms in a starfish?", "options": ["4", "5", "6", "7"], "answer": "5"},
    {"question": "First Indian woman in space?", "options": ["Sunita Williams", "Kalpana Chawla", "Indira Gandhi", "Rani Laxmi Bai"], "answer": "Kalpana Chawla"},
    {"question": "National anthem of India?", "options": ["Jana Gana Mana", "Vande Mataram", "Sare Jahan Se Achha", "Mile Sur Mera Tumhara"], "answer": "Jana Gana Mana"}
]

}
